name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Check if Dockerfile changed
        run: | 
          echo "DOCKERFILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -c Dockerfile)" >> $GITHUB_ENV \
          && echo $DOCKERFILE_CHANGED
      - 
        name: Get branch name
        run: | 
          echo "BRANCH_NAME=$(basename -- "${{ github.ref }}")" >> $GITHUB_ENV \
          && echo $BRANCH_NAME
      - 
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: bensampson5/openhdl
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    if: always()
    needs: [docker-build]
    runs-on: ubuntu-latest
    container: bensampson5/openhdl:main
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          mkdir build \
          && cd build \
          && cmake -GNinja .. \
          && ninja
      -
        name: Run tests
        run: |
          cd build/test \
          && ./test_main