name: docker-retag

# on: create
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  docker-retag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get new branch name
        run: echo "BRANCH_NAME=$(basename -- "${{ github.ref }}")" >> $GITHUB_ENV
      - 
        name: Print branch name
        run: echo $BRANCH_NAME
