name: docker-retag

# on: create
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  docker-retag:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Echo branch name
        run: echo "github.sha = ${{ github.sha }}, github.ref = ${{ github.ref }}"

