name: docker-retag

# on: create
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  docker-retag:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Print branch name
        run: echo ${ ${{github.ref}}##*/ }

